hl.unbind("F23")
hl.bind("F23", hl.dsp.exec_cmd("~/.local/bin/fercds/menu/toggle_fercds.sh"))
hl.unbind("SUPER + D")
hl.bind("SUPER + D", hl.dsp.exec_cmd("/usr/bin/toggle_wvkbd.sh"), { locked = true, description = "Keyboard" })
hl.unbind("SUPER + G")
hl.bind("SUPER + G", hl.dsp.exec_cmd("/usr/bin/cprofile.sh"), { locked = true })
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"))
hl.unbind("F19")
hl.bind("F19", hl.dsp.focus({ workspace = "m+1" }))
hl.bind("F19", hl.dsp.exec_cmd("paplay ~/.local/share/sounds/nintendold/stereo/desktop-switch-right.wav"))
hl.unbind("F24")
hl.bind("F24", hl.dsp.focus({ workspace = "m-1" }))
hl.bind("F24", hl.dsp.exec_cmd("paplay ~/.local/share/sounds/nintendold/stereo/desktop-switch-right.wav"))
hl.unbind("SUPER + CTRL + Q")
hl.bind("SUPER + CTRL + Q", hl.dsp.window.kill(), { description = "Force Kill Window" })
hl.unbind("SUPER + M")
hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.window.close(), { description = "Close Window (by selector)" })
hl.unbind("SUPER + T")
hl.unbind("SUPER + mouse:273")
